@startuml
Class Namespace{
-Map<String,Symbol> symbols
}
Namespace -- Symbol 
Record -- Namespace
Abstract class Type{

}

Class Array{
-Type type
}
Class Primitive{
-Int size
}
Class Record{
-Namespace<Variable> namespace
}
Type <|--Array
Type <|--Primitive
Type <|-- Record


Abstract class Symbol{

}
Abstract class FunctionOrVariable{

}
Class Function{
-Type type
-SymbolTable table
}
Class Variable{
-Type type
-int shift
}
Symbol <|-- FunctionOrVariable
FunctionOrVariable <|-- Function
SymbolTable -- Function
FunctionOrVariable <|--Variable
Symbol <|-- Type



Class SymbolTable{
-SymbolTableParent
-ArrayList<SymbolTable> children
-Namespace<Type> types
-Namespace<FunctionOrVariable> functsAndVard
}
SymbolTable--"*"SymbolTable
SymbolTable --Namespace
@enduml
