@startuml

Class TigerTranslator{
  +String toString()
}

Class Writer{
  +Writer(LabelGenerator)
  +void writeHeader(String label, String statement)
  +void writeHeader(String statement)
  +void writeHeader()
  +void writeMainLine(String line)
  +void writeMain(String label, String statement)
  +void writeMain(String statement)
  +void writeFunctionLine(String line)
  +void writeFunction(String label, String statement)
  +void writeFunction(String statement)
  +void descend()
  +void ascend()
  +String toString()
}

Class LabelGenerator{
  +LabelGenerator(int maxLengthOfLabel)
  +String padLabel(String string)
  +String getIndent()
  +String getLabel(SymbolTable table, String name)
  +String getLabel(SymbolTable symbolTable)
  +String getLabel(Tree tree, String key)
}

Class RegisterManager{
  +RegisterManager(Writer)
  +void descend()
  +void ascend()
  +int saveAll()
  +void restoreAll()
  +int provideRegister()
  +void freeRegister()
}

TigerTranslator "0" -- "1\ncurrentTDS" SymbolTable
TigerTranslator "0" -- "1" Writer
TigerTranslator "0" -- "1" LabelGenerator
TigerTranslator "0" -- "1" RegisterManager

Writer "0" -- "1" LabelGenerator
RegisterManager "0" -- "1" Writer

Class SymbolTable{
  +HashMap<Tree, Type> treeTypeHashMap
-SymbolTable symbolTableParent
-ArrayList<SymbolTable> children
-Namespace<Type> types
-Namespace<FunctionOrVariable> functsAndVard
}
SymbolTable--"*" SymbolTable
@enduml
